Github actions. Work on v2 backup strategy

diff --git a/.github/actions/backup_v2/action.yaml b/.github/actions/backup_v2/action.yaml
--- a/.github/actions/backup_v2/action.yaml
+++ b/.github/actions/backup_v2/action.yaml
@@ -33,8 +33,7 @@ runs:
   using: 'composite'
   steps:
     - name: Install Rclone
-      run: |
-        sudo -v ; curl https://rclone.org/install.sh | sudo bash
+      run: sudo -v ; curl https://rclone.org/install.sh | sudo bash
       shell: bash
 
     - name: Verify Installation
@@ -51,6 +50,42 @@ runs:
     - name: Perform the backup and push to S3
       run: |
         chmod +x ./.github/actions/backup_v2/backup_v2.sh
-        ./.github/actions/backup_v2/backup_v2.sh "${{ inputs.environment }}" "${{ inputs.project-name }}" "${{ inputs.site-name }}" "${{ inputs.openshift-server }}" "${{ inputs.dev-token }}" "${{ inputs.test-token }}" "${{ inputs.prod-token }}" "${{ inputs.s3-token }}" 
+
+        set +e
+        CMD_RESULTS=$( ./.github/actions/backup_v2/backup_v2.sh "${{ inputs.environment }}" "${{ inputs.project-name }}" "${{ inputs.site-name }}" "${{ inputs.openshift-server }}" "${{ inputs.dev-token }}" "${{ inputs.test-token }}" "${{ inputs.prod-token }}" "${{ inputs.s3-token }}")
+        CMD_EXIT_CODE=$?
+        set -e
+
+        if [[ $CMD_EXIT_CODE -eq 0 ]]; then
+          echo "Success creating backup"
+          echo "$CMD_RESULTS"
+
+        else
+          #try a 2nd time
+          echo "Error creating backup 1st time, "
+          echo "Code: $CMD_EXIT_CODE"
+          echo "$CMD_RESULTS"
+
+          echo "Retrying..."
+          set +e
+          CMD_RESULTS=$( ./.github/actions/backup_v2/backup_v2.sh "${{ inputs.environment }}" "${{ inputs.project-name }}" "${{ inputs.site-name }}" "${{ inputs.openshift-server }}" "${{ inputs.dev-token }}" "${{ inputs.test-token }}" "${{ inputs.prod-token }}" "${{ inputs.s3-token }}")
+          CMD_EXIT_CODE=$?
+          set -e
+
+          if [[ $CMD_EXIT_CODE -eq 0 ]]; then
+            echo "Success creating backup on 2nd try."
+            echo "$CMD_RESULTS"
+
+          else
+            echo "Error creating backup 2nd time, "
+            echo "Code: $CMD_EXIT_CODE"
+            echo "$CMD_RESULTS"
+
+            exit $CMD_EXIT_CODE
+          fi
+        fi
+
+        
+
       shell: bash
           
