Github actions. Initial pass at a v2 backup strategy

diff --git a/.github/workflows/backup-bb-v2.yaml b/.github/workflows/backup-bb-v2.yaml
--- a/.github/workflows/backup-bb-v2.yaml
+++ b/.github/workflows/backup-bb-v2.yaml
@@ -84,13 +84,28 @@ jobs:
           echo "::group::Create DB backup"
           echo "DB Pod Name: $DB_POD_NAME"
           echo "DB Container Name: $DB_CONTAINER_NAME"  
+
+          set +e
           CMD1_RESULTS=$(oc exec -n $NAMESPACE -c $DB_CONTAINER_NAME $DB_POD_NAME -- sh -c 'mariadb-dump  -u root -p$(cat $MYSQL_ROOT_PASSWORD_FILE) $MYSQL_DATABASE | gzip' > db.sql.gz 2>&1)
           CMD1_EXIT_CODE=$?
-          #echo "${CMD1_RESULTS}"
-          du -sh db.sql.gz
+          set -e
+	        if [ CMD1_EXIT_CODE -eq 0 ]; then
+            echo "Success creating database backup"
+            echo "Code: $CMD1_EXIT_CODE"
+            echo "$CMD1_RESULTS"
+            du -sh db.sql.gz
 
-          LOCAL_MD5=($(md5sum ./db.sql.gz))
-          echo "-- MD5 of db backup file: $LOCAL_MD5"
+            LOCAL_MD5=($(md5sum ./db.sql.gz))
+            echo "-- MD5 of db backup file: $LOCAL_MD5"
+
+          else
+            echo "Error creating database backup:"
+            echo "Code: $CMD1_EXIT_CODE"
+            echo "$CMD1_RESULTS"
+            exit 0
+          fi
+
+          
           echo "::endgroup::"
 
 
