Github actions. Work on v2 backup strategy

diff --git a/.github/workflows/list-backups-v2.yaml b/.github/workflows/list-backups-v2.yaml
--- a/.github/workflows/list-backups-v2.yaml
+++ b/.github/workflows/list-backups-v2.yaml
@@ -11,7 +11,7 @@ on:
         - cleanbcdx-ge
         - cleanbcdx-bb
         - cleanbc
-        default: 'cleanbcdx-bb'
+        default: 'cleanbcdx-bh'
 
       site-name:
         description: 'Site name'
@@ -33,12 +33,40 @@ jobs:
 
       - name: Get list of backups
         run: |
+          PROJECT_NAME=${{ github.event.inputs.project-name }}
+          SITE_NAME=${{ github.event.inputs.site-name }}
           ENVIRONMENT=prod
-          oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOOLS_API_TOKEN  }}
           NAMESPACE="f181a8-$ENVIRONMENT"
 
+
+          echo "Getting list of backups for $PROJECT_NAME" 
+
           
-          CMD_RESULTS=$(rclone lsf :s3:clbcdx/oc-sites-bk --include "$PROJECT_NAME-${{ github.event.inputs.site-name }}_$ENVIRONMENT_*_backup.tar*" --files-only --s3-provider Other --s3-access-key-id "nr-cleanbcdx-pr" --s3-secret-access-key "$S3_TOKEN" --s3-endpoint "https://nrs.objectstore.gov.bc.ca"  --contimeout "15s" --retries 3 | sort | tail -n 20)
+          # Log in to OpenShift
+          echo "::group::Login to target OC"
+          #Sometimes oc login will fail to connect, so lets re-try on failure.
+          set +e
+          oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOOLS_API_TOKEN  }}
+          ret=$?
+          set -e
+          if [ $ret -eq 0 ]; then
+              # The command was successful
+              echo "Login successful"
+
+          else
+              echo "Re-trying oc-login in 10s..."
+
+              sleep 10
+
+              # The command was not successful, lets try again
+              oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOOLS_API_TOKEN  }}
+
+          fi
+
+          echo "::endgroup::"
+          
+          
+          CMD_RESULTS=$(rclone lsf :s3:clbcdx/oc-sites-bk --include "$PROJECT_NAME-$SITE_NAME_$ENVIRONMENT_*_backup.tar*" --files-only --s3-provider Other --s3-access-key-id "nr-cleanbcdx-pr" --s3-secret-access-key "$S3_TOKEN" --s3-endpoint "https://nrs.objectstore.gov.bc.ca"  --contimeout "15s" --retries 3 | sort | tail -n 20)
 
           if [ -z "$CMD_RESULTS" ]; then
               echo "::error::Unknown backup file name: ${CMD_RESULTS}"
